version: "3.7"

services:
  web:
    image: githubyumao/mcsmanager-web:latest
    restart: unless-stopped
    environment:
      - PORT=23333
      - MC_PATH=/minecraft
    volumes:
      - ${APP_DATA_DIR}/data:/minecraft
    depends_on:
      - daemon

  daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    environment:
      - PORT=23334
      - WEBHOOK=http://web:23333
    volumes:
      - ${APP_DATA_DIR}/data:/minecraft
